name: CMake Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

  VCPKG_INSTALL_OPTIONS: --x-abi-tools-use-exact-versions

  VCPKG_DISABLE_COMPILER_TRACKING: ON
  VCPKG_DEFAULT_TRIPLET: x64-windows

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Set vcpkg environment variables
      shell: bash
      run: |
        echo "VCPKG_ROOT=C:/vcpkg" >> $GITHUB_ENV

        echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $GITHUB_ENV

    - name: Restore vcpkg cache
      id: cache-vcpkg
      uses: actions/cache@v3
      with:
        path: |
          C:/vcpkg/installed
          C:/vcpkg/buildtrees
          C:/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: 'C:/vcpkg'
        vcpkgGitURL: 'https://github.com/microsoft/vcpkg.git'
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Update vcpkg cache
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: |
          C:/vcpkg/installed
          C:/vcpkg/buildtrees
          C:/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}

    - name: Configure CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: 'windows-vs2022-vcpkg'
        buildPreset: 'windows-vs2022-vcpkg'
 

    - name: Build project
      run: cmake --build "${{ github.workspace }}/build/windows-vs2022-vcpkg" 

    # Optional: Add a step to run tests if applicable
    # - name: Run tests
    #   run: ctest --output-on-failure

    - name: Artifact Upload (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: '${{ github.workspace }}/build/windows-vs2022-vcpkg'
