name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  VCPKG_INSTALL_OPTIONS: --x-abi-tools-use-exact-versions
  VCPKG_BUILD_TYPE: release
  VCPKG_DISABLE_COMPILER_TRACKING: ON
  VCPKG_DEFAULT_TRIPLET: x64-windows

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Set vcpkg environment variables
        shell: bash
        run: |
          echo "VCPKG_ROOT=C:/vcpkg" >> $GITHUB_ENV
          echo "VCPKG_BUILD_TYPE=release" >> $GITHUB_ENV
          echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $GITHUB_ENV

      - name: Create buildtrees_short directory
        run: mkdir C:\vcpkg\buildtrees_short
        shell: cmd

      - name: Run vcpkg
        id: runvcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: 'C:/vcpkg'
          vcpkgGitURL: 'https://github.com/microsoft/vcpkg.git'
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgFormatString: '--triplet ${VCPKG_DEFAULT_TRIPLET} install --x-buildtrees-root=C:/vcpkg/buildtrees_short'

      - name: Run CMake with vcpkg (Release configuration)
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'windows-vs2022-vcpkg'
          buildPreset: 'windows-vs2022-vcpkg'
          buildPresetAdditionalArgs: '--config Release'

      # Add any additional steps you need
